name: Build-and-Deploy

# credit to @mwm126

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish:
    # Name the Job
    name: Build Sphinx docs HTML target
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sphinx
        run: pip install sphinx sphinx-rtd-theme

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean docs build
        run: make -C docs clean

      - name: Build docs in HTML 
        run: make -C docs html
        env:
          DEFAULT_BRANCH: main
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: No jekyll, bad jekyll 
        run: touch docs/_build/html/.nojekyll 

      - name: Deploy to GitHub Pages Branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
